In [ ]:
 #K = centrid ; N = nearest ; N = neighbors
 import pandas as pd
 import numpy as np
 import matplotlib.pyplot as plt

In [ ]:
from pandas import read_csv
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
from google.colab import files
data = files.upload()

Saving gender classification.zip to gender classification.zip


In [ ]:
df = read_csv('gender classification.zip')

In [ ]:
df

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0             1               11.8                 6.1          1          0   
1             0               14.0                 5.4          0          0   
2             0               11.8                 6.3          1          1   
3             0               14.4                 6.1          0          1   
4             1               13.5                 5.9          0          0   
...         ...                ...                 ...        ...        ...   
4996          1               13.6                 5.1          0          0   
4997          1               11.9                 5.4          0          0   
4998          1               12.9                 5.7          0          0   
4999          1               13.2                 6.2          0          0   
5000          1               15.4                 5.4          1          1   

      lips_thin  distance_nose_to_lip_long  gender  
0             1                          1    Male  
1             1                          0  Female  
2             1                          1    Male  
3             1                          1    Male  
4             0                          0  Female  
...         ...                        ...     ...  
4996          0                          0  Female  
4997          0                          0  Female  
4998          0                          0  Female  
4999          0                          0  Female  
5000          1                          1    Male  

[5001 rows x 8 columns]

In [ ]:
data_array = df.values

In [ ]:
data_array

array([[1, 11.8, 6.1, ..., 1, 1, 'Male'],
       [0, 14.0, 5.4, ..., 1, 0, 'Female'],
       [0, 11.8, 6.3, ..., 1, 1, 'Male'],
       ...,
       [1, 12.9, 5.7, ..., 0, 0, 'Female'],
       [1, 13.2, 6.2, ..., 0, 0, 'Female'],
       [1, 15.4, 5.4, ..., 1, 1, 'Male']], dtype=object)

In [ ]:
x = data_array[:,0:7]

In [ ]:
x

array([[1, 11.8, 6.1, ..., 0, 1, 1],
       [0, 14.0, 5.4, ..., 0, 1, 0],
       [0, 11.8, 6.3, ..., 1, 1, 1],
       ...,
       [1, 12.9, 5.7, ..., 0, 0, 0],
       [1, 13.2, 6.2, ..., 0, 0, 0],
       [1, 15.4, 5.4, ..., 1, 1, 1]], dtype=object)

In [ ]:
y = data_array[:,7]
y

array(['Male', 'Female', 'Male', ..., 'Female', 'Female', 'Male'],
      dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20,random_state=0)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=9,p=2)
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=9)

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
y_pred

array(['Female', 'Male', 'Male', ..., 'Female', 'Male', 'Female'],
      dtype=object)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [ ]:
cm

array([[501,  17],
       [ 19, 464]])