In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
data = files.upload()

Saving GENDER CLASSIFICATION.zip to GENDER CLASSIFICATION.zip


In [ ]:
df = pd.read_csv('GENDER CLASSIFICATION.zip')

In [ ]:
df

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0             1               11.8                 6.1          1          0   
1             0               14.0                 5.4          0          0   
2             0               11.8                 6.3          1          1   
3             0               14.4                 6.1          0          1   
4             1               13.5                 5.9          0          0   
...         ...                ...                 ...        ...        ...   
4996          1               13.6                 5.1          0          0   
4997          1               11.9                 5.4          0          0   
4998          1               12.9                 5.7          0          0   
4999          1               13.2                 6.2          0          0   
5000          1               15.4                 5.4          1          1   

      lips_thin  distance_nose_to_lip_long  gender  
0             1                          1    Male  
1             1                          0  Female  
2             1                          1    Male  
3             1                          1    Male  
4             0                          0  Female  
...         ...                        ...     ...  
4996          0                          0  Female  
4997          0                          0  Female  
4998          0                          0  Female  
4999          0                          0  Female  
5000          1                          1    Male  

[5001 rows x 8 columns]

In [ ]:
df['forehead_width_cm'].unique()

array([11.8, 14. , 14.4, 13.5, 13. , 15.3, 11.9, 12.1, 12.5, 15.5, 14.7,
       14.5, 14.2, 15.2, 14.6, 12.8, 12.9, 12.2, 12.3, 12.7, 14.1, 11.5,
       13.8, 13.7, 12. , 11.4, 15.4, 13.3, 13.2, 14.3, 13.9, 11.7, 15.1,
       15. , 12.4, 11.6, 12.6, 14.8, 13.1, 13.4, 13.6, 14.9])

In [ ]:
from sklearn import preprocessing

# **Label** **Encoder**



In [ ]:
label_encoder = preprocessing.LabelEncoder()
df['forehead_width_cm'] = label_encoder.fit_transform(df['forehead_width_cm'])

In [ ]:
df

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0             1                  4                 6.1          1          0   
1             0                 26                 5.4          0          0   
2             0                  4                 6.3          1          1   
3             0                 30                 6.1          0          1   
4             1                 21                 5.9          0          0   
...         ...                ...                 ...        ...        ...   
4996          1                 22                 5.1          0          0   
4997          1                  5                 5.4          0          0   
4998          1                 15                 5.7          0          0   
4999          1                 18                 6.2          0          0   
5000          1                 40                 5.4          1          1   

      lips_thin  distance_nose_to_lip_long  gender  
0             1                          1    Male  
1             1                          0  Female  
2             1                          1    Male  
3             1                          1    Male  
4             0                          0  Female  
...         ...                        ...     ...  
4996          0                          0  Female  
4997          0                          0  Female  
4998          0                          0  Female  
4999          0                          0  Female  
5000          1                          1    Male  

[5001 rows x 8 columns]

In [ ]:
df['forehead_width_cm'].unique()

array([ 4, 26, 30, 21, 16, 39,  5,  7, 11, 41, 33, 31, 28, 38, 32, 14, 15,
        8,  9, 13, 27,  1, 24, 23,  6,  0, 40, 19, 18, 29, 25,  3, 37, 36,
       10,  2, 12, 34, 17, 20, 22, 35])

# **Get Dummies**

In [ ]:
pd.get_dummies('gender')

gender
0       1

In [ ]:
df.dtypes

long_hair                      int64
forehead_width_cm              int64
forehead_height_cm           float64
nose_wide                      int64
nose_long                      int64
lips_thin                      int64
distance_nose_to_lip_long      int64
gender                        object
dtype: object

# **One Hot Encoder**

In [ ]:
ec = preprocessing.OneHotEncoder()

In [ ]:
ec_transformed = ec.fit_transform(df[['nose_wide']]).toarray()

In [ ]:
ec_transformed

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 1.]])